#!/bin/sh

echo syncing engine...
sh /usr/bin/update-engine.sh
echo syncing games...
/spring-engines/latest/pr-downloader --filesystem-writepath /spring-data byar:test
echo syncing maps...
sh /usr/bin/sync-maps.sh
